#!/bin/bash

# 迁移现有的硬编码 API Key 到配置文件

SKILL_DIR="$HOME/.claude/skills/ding-check"
CONFIG_FILE="$SKILL_DIR/config.sh"

echo "🔧 ding-check Skill 配置迁移工具"
echo ""

# 检查是否已有配置
if [[ -f "$CONFIG_FILE" ]]; then
    echo "✓ 发现现有配置文件: $CONFIG_FILE"
    echo ""
    read -p "是否要更新配置？(y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "已取消"
        exit 0
    fi
fi

# 提示输入 API Key
echo "请输入您的 Gemini API Key："
echo "（获取地址：https://aistudio.google.com/app/apikey）"
echo ""
read -p "API Key: " api_key

if [[ -z "$api_key" ]]; then
    echo "❌ API Key 不能为空"
    exit 1
fi

# 创建配置文件
mkdir -p "$SKILL_DIR"
cat > "$CONFIG_FILE" << CONFIGEOF
# Gemini API Key for ding-check skill
# Generated by migrate-config.sh at $(date)

export GEMINI_API_KEY='$api_key'

# Optional: Proxy settings (uncomment if needed)
# export HTTP_PROXY="http://127.0.0.1:7890"
# export HTTPS_PROXY="http://127.0.0.1:7890"
CONFIGEOF

# 设置权限
chmod 600 "$CONFIG_FILE"

echo ""
echo "✅ 配置已保存到: $CONFIG_FILE"
echo "✓ 文件权限已设置为 600（仅用户可读写）"
echo ""
echo "现在可以安全地分享 skill.sh 给其他用户了！"
echo ""
echo "💡 提示："
echo "  - config.sh 已被 .gitignore 排除，不会被提交到 Git"
echo "  - 其他用户需要创建自己的 config.sh 并填入自己的 API Key"
echo "  - 运行 /ding-check 首次使用时会自动引导配置"
